version: "2"
services:
  airfec:
    container_name: airfec_photos
    build: .
    image: airfec_photos
    ports:
      - '80:3000'
    environment:
      - MONGODB_URI=mongo_server
      - PORT=3000
    depends_on:
      - 'database'
    links: 
      - database:mongo_server
  database:
    container_name: mongo
    image: mongo:latest